/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProyectoV1;

/**
 *
 * @author Dayana
 */
public class Derepuesto extends javax.swing.JFrame {

    /**
     * Creates new form Derepuesto
     */
    public Derepuesto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bntGuardarUsuario = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlFondo.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 140, -1));
        pnlFondo.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 140, -1));
        pnlFondo.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 140, -1));
        pnlFondo.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 130, -1));
        pnlFondo.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 130, -1));
        pnlFondo.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 130, -1));

        lblCorreo.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblCorreo.setText("Correo:");
        pnlFondo.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, -1, -1));

        lblTelefono.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblTelefono.setText("Teléfono:");
        pnlFondo.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        lblCedula.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblCedula.setText("Cédula:");
        pnlFondo.add(lblCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));

        lblDireccion.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblDireccion.setText("Dirección:");
        pnlFondo.add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        lblApellido.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblApellido.setText("Apellido:");
        pnlFondo.add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        lblNombre.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblNombre.setText("Nombre:");
        pnlFondo.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel8.setText("D E R R");
        pnlFondo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 100, -1));

        bntGuardarUsuario.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        bntGuardarUsuario.setText("GUARDAR USUARIO");
        pnlFondo.add(bntGuardarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel9.setText("Seleccione el género de ropa que desea ver ...");
        pnlFondo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 320, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logotipo circular  recta mediano.png"))); // NOI18N
        pnlFondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 170, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Derepuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Derepuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Derepuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Derepuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Derepuesto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntGuardarUsuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
