/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProyectoV1;

import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class GUI_PrendasBasicasH extends javax.swing.JFrame {
Prenda prenda;
    /**
     * Creates new form GUI_PrendasBasicasH
     */
    public GUI_PrendasBasicasH() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgLeva = new javax.swing.ButtonGroup();
        btgCamiseta = new javax.swing.ButtonGroup();
        btgCamisetaCuadros = new javax.swing.ButtonGroup();
        btgPantalonTela = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnAtrasPrendasBasicasHombre = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        spnCamiseta = new javax.swing.JSpinner();
        jLabel31 = new javax.swing.JLabel();
        cmbCamiseta = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        btnGuardarCamiseta = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        rbtSCamiseta = new javax.swing.JRadioButton();
        rbtMCamiseta = new javax.swing.JRadioButton();
        rbtLCamiseta = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        spnLeva = new javax.swing.JSpinner();
        jLabel35 = new javax.swing.JLabel();
        cmbLeva = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        btnGuardarLeva = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        rbtSLeva = new javax.swing.JRadioButton();
        rbtMLeva = new javax.swing.JRadioButton();
        rbtLLeva = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        spnCamisaCuadros = new javax.swing.JSpinner();
        jLabel43 = new javax.swing.JLabel();
        cmbCamisaCuadros = new javax.swing.JComboBox<>();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        btnGuardarCamisaCuadros = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        rbtSCamisaCuadros = new javax.swing.JRadioButton();
        rbtMCamisaCuadros = new javax.swing.JRadioButton();
        rbtLCamisaCuadros = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        spnPantalonTela = new javax.swing.JSpinner();
        jLabel39 = new javax.swing.JLabel();
        cmbPantalonTela = new javax.swing.JComboBox<>();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        btnGuardarPantalonTela = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        rbtSPantalonTela = new javax.swing.JRadioButton();
        rbtMPantalonTela = new javax.swing.JRadioButton();
        rbtLPantalonTela = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnIrPrincipal = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setPreferredSize(new java.awt.Dimension(750, 660));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAtrasPrendasBasicasHombre.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnAtrasPrendasBasicasHombre.setText("Atrás");
        btnAtrasPrendasBasicasHombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasPrendasBasicasHombreActionPerformed(evt);
            }
        });
        jPanel4.add(btnAtrasPrendasBasicasHombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, -1, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel31.setText("¿Cuántos desea adquirir?");

        cmbCamiseta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blanco", "Negro ", "Vino", " ", " " }));
        cmbCamiseta.setSelectedIndex(-1);
        cmbCamiseta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCamisetaActionPerformed(evt);
            }
        });

        jLabel32.setText("Precio:   $ 12.00 c/u");

        jLabel33.setText("Talla:");

        btnGuardarCamiseta.setText("Guardar");
        btnGuardarCamiseta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCamisetaActionPerformed(evt);
            }
        });

        jLabel34.setText("Color:");

        btgCamiseta.add(rbtSCamiseta);
        rbtSCamiseta.setText("S");

        btgCamiseta.add(rbtMCamiseta);
        rbtMCamiseta.setText("M");

        btgCamiseta.add(rbtLCamiseta);
        rbtLCamiseta.setText("L");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Basicos/camiseta h.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText("Camiseta");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(spnCamiseta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtSCamiseta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtMCamiseta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtLCamiseta))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuardarCamiseta)
                            .addComponent(cmbCamiseta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel15)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnCamiseta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(rbtSCamiseta)
                            .addComponent(rbtMCamiseta)
                            .addComponent(rbtLCamiseta))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbCamiseta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34))
                        .addGap(23, 23, 23)
                        .addComponent(btnGuardarCamiseta))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 290, 250));

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel35.setText("¿Cuántos desea adquirir?");

        cmbLeva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blanco", "Negro ", "Vino", " ", " " }));
        cmbLeva.setSelectedIndex(-1);
        cmbLeva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLevaActionPerformed(evt);
            }
        });

        jLabel36.setText("Precio:   $ 35.00 c/u");

        jLabel37.setText("Talla:");

        btnGuardarLeva.setText("Guardar");
        btnGuardarLeva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarLevaActionPerformed(evt);
            }
        });

        jLabel38.setText("Color:");

        btgLeva.add(rbtSLeva);
        rbtSLeva.setText("S");

        btgLeva.add(rbtMLeva);
        rbtMLeva.setText("M");

        btgLeva.add(rbtLLeva);
        rbtLLeva.setText("L");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Basicos/leva.png"))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("Leva");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36)
                    .addComponent(spnLeva, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtSLeva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtMLeva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtLLeva))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuardarLeva)
                            .addComponent(cmbLeva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel16)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnLeva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel37)
                            .addComponent(rbtSLeva)
                            .addComponent(rbtMLeva)
                            .addComponent(rbtLLeva))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbLeva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel38))
                        .addGap(23, 23, 23)
                        .addComponent(btnGuardarLeva))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 300, 250));

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel43.setText("¿Cuántos desea adquirir?");

        cmbCamisaCuadros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blanco", "Negro ", "Vino", " ", " " }));
        cmbCamisaCuadros.setSelectedIndex(-1);
        cmbCamisaCuadros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCamisaCuadrosActionPerformed(evt);
            }
        });

        jLabel44.setText("Precio:   $ 13.00 c/u");

        jLabel45.setText("Talla:");

        btnGuardarCamisaCuadros.setText("Guardar");
        btnGuardarCamisaCuadros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCamisaCuadrosActionPerformed(evt);
            }
        });

        jLabel46.setText("Color:");

        btgCamisetaCuadros.add(rbtSCamisaCuadros);
        rbtSCamisaCuadros.setText("S");

        btgCamisetaCuadros.add(rbtMCamisaCuadros);
        rbtMCamisaCuadros.setText("M");

        btgCamisetaCuadros.add(rbtLCamisaCuadros);
        rbtLCamisaCuadros.setText("L");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Basicos/camiseta a cuadros.png"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setText("Camisa a cuadros");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel46)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuardarCamisaCuadros)
                            .addComponent(cmbCamisaCuadros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel45)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtSCamisaCuadros)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtMCamisaCuadros)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbtLCamisaCuadros))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel44)
                                    .addComponent(spnCamisaCuadros, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel43))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel18)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel44)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel43)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnCamisaCuadros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel45)
                            .addComponent(rbtSCamisaCuadros)
                            .addComponent(rbtMCamisaCuadros)
                            .addComponent(rbtLCamisaCuadros))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbCamisaCuadros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel46))
                        .addGap(23, 23, 23)
                        .addComponent(btnGuardarCamisaCuadros))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel39.setText("¿Cuántos desea adquirir?");

        cmbPantalonTela.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blanco", "Negro ", "Vino", " ", " " }));
        cmbPantalonTela.setSelectedIndex(-1);
        cmbPantalonTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPantalonTelaActionPerformed(evt);
            }
        });

        jLabel40.setText("Precio:   $ 15.00 c/u");

        jLabel41.setText("Talla:");

        btnGuardarPantalonTela.setText("Guardar");
        btnGuardarPantalonTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPantalonTelaActionPerformed(evt);
            }
        });

        jLabel42.setText("Color:");

        btgPantalonTela.add(rbtSPantalonTela);
        rbtSPantalonTela.setText("S");

        btgPantalonTela.add(rbtMPantalonTela);
        rbtMPantalonTela.setText("M");

        btgPantalonTela.add(rbtLPantalonTela);
        rbtLPantalonTela.setText("L");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Basicos/pantalón de tela.png"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setText("Pantalón de tela");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40)
                    .addComponent(spnPantalonTela, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtSPantalonTela)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtMPantalonTela, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtLPantalonTela))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuardarPantalonTela)
                            .addComponent(cmbPantalonTela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel17)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnPantalonTela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel41)
                            .addComponent(rbtSPantalonTela)
                            .addComponent(rbtMPantalonTela)
                            .addComponent(rbtLPantalonTela))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbPantalonTela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel42))
                        .addGap(23, 23, 23)
                        .addComponent(btnGuardarPantalonTela))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Hoja en blanco.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 560));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 650, -1));

        btnIrPrincipal.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnIrPrincipal.setText("Principal");
        btnIrPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrPrincipalActionPerformed(evt);
            }
        });
        jPanel4.add(btnIrPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 610, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Basicos/FondoPrendasBasicasHombre.png"))); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, 0, 950, 660));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCamisetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCamisetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCamisetaActionPerformed

    private void btnGuardarCamisetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCamisetaActionPerformed
        // TODO add your handling code here:

        String nombre = "Camiseta";
        double precio = 12;
        int cantidad;
        char talla;
        String color;

        if (rbtSCamiseta.isSelected() == false && rbtMCamiseta.isSelected() == false && rbtLCamiseta.isSelected() == false){
            JOptionPane.showMessageDialog(null, "Porfavor, debe escoger una talla");
        }
        else{

            cantidad = Integer.parseInt(spnCamiseta.getValue().toString());

            if(rbtSCamiseta.isSelected()){
                talla = 'S';
            }
            else{
                if(rbtMCamiseta.isSelected()){
                    talla = 'M';
                }
                else{
                    talla = 'L';
                }
            }
            

            color = cmbCamiseta.getSelectedItem().toString();

            prenda = new Prenda (nombre, precio, cantidad, talla, color);
            }
    }//GEN-LAST:event_btnGuardarCamisetaActionPerformed

    private void cmbLevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLevaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbLevaActionPerformed

    private void btnGuardarLevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarLevaActionPerformed
        // TODO add your handling code here:

        String nombre = "Leva";
        double precio = 35;
        int cantidad;
        char talla;
        String color;

        if (rbtSLeva.isSelected() == false && rbtMLeva.isSelected() == false && rbtLLeva.isSelected() == false){
            JOptionPane.showMessageDialog(null, "Porfavor, debe escoger una talla");
        }
        else{

            cantidad = Integer.parseInt(spnLeva.getValue().toString());

            if(rbtSLeva.isSelected()){
                talla = 'S';
            }
            else{
                if(rbtMLeva.isSelected()){
                    talla = 'M';
                }
                else{
                    talla = 'L';
                }
            }

            color = cmbLeva.getSelectedItem().toString();

            prenda = new Prenda (nombre, precio, cantidad, talla, color);
             }
    }//GEN-LAST:event_btnGuardarLevaActionPerformed

    private void cmbPantalonTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPantalonTelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPantalonTelaActionPerformed

    private void btnGuardarPantalonTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPantalonTelaActionPerformed
        // TODO add your handling code here:
 String nombre = "Pantalón de tela";
        double precio = 15;
        int cantidad;
        char talla;
        String color;

        if (rbtSPantalonTela.isSelected() == false && rbtMPantalonTela.isSelected() == false && rbtLPantalonTela.isSelected() == false){
            JOptionPane.showMessageDialog(null, "Porfavor, debe escoger una talla");
        }
        else{

            cantidad = Integer.parseInt(spnPantalonTela.getValue().toString());

            if(rbtSPantalonTela.isSelected()){
                talla = 'S';
            }
            else{
                if(rbtMPantalonTela.isSelected()){
                    talla = 'M';
                }
                else{
                    talla = 'L';
                }
            }

            color = cmbPantalonTela.getSelectedItem().toString();

            prenda = new Prenda (nombre, precio, cantidad, talla, color);
            }
    }//GEN-LAST:event_btnGuardarPantalonTelaActionPerformed

    private void cmbCamisaCuadrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCamisaCuadrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCamisaCuadrosActionPerformed

    private void btnGuardarCamisaCuadrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCamisaCuadrosActionPerformed
        // TODO add your handling code here:

       String nombre = "Camisa a cuadros";
        double precio = 13;
        int cantidad;
        char talla;
        String color;

        if (rbtSCamisaCuadros.isSelected() == false && rbtMCamisaCuadros.isSelected() == false && rbtLCamisaCuadros.isSelected() == false){
            JOptionPane.showMessageDialog(null, "Porfavor, debe escoger una talla");
        }
        else{

            cantidad = Integer.parseInt(spnCamisaCuadros.getValue().toString());

            if(rbtSCamisaCuadros.isSelected()){
                talla = 'S';
            }
            else{
                if(rbtMCamisaCuadros.isSelected()){
                    talla = 'M';
                }
                else{
                    talla = 'L';
                }
            }

            color = cmbCamisaCuadros.getSelectedItem().toString();

            prenda = new Prenda (nombre, precio, cantidad, talla, color);
            }
    }//GEN-LAST:event_btnGuardarCamisaCuadrosActionPerformed

    private void btnAtrasPrendasBasicasHombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasPrendasBasicasHombreActionPerformed
        // TODO add your handling code here:
      GUI_PrendasBasicasM atras = new GUI_PrendasBasicasM();
        atras.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAtrasPrendasBasicasHombreActionPerformed

    private void btnIrPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrPrincipalActionPerformed
        // TODO add your handling code here:
         GUI_Principal irPrincipal = new GUI_Principal();
        irPrincipal.setVisible(true);
        dispose();
                    
    }//GEN-LAST:event_btnIrPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_PrendasBasicasH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_PrendasBasicasH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_PrendasBasicasH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_PrendasBasicasH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_PrendasBasicasH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgCamiseta;
    private javax.swing.ButtonGroup btgCamisetaCuadros;
    private javax.swing.ButtonGroup btgLeva;
    private javax.swing.ButtonGroup btgPantalonTela;
    private javax.swing.JButton btnAtrasPrendasBasicasHombre;
    private javax.swing.JButton btnGuardarCamisaCuadros;
    private javax.swing.JButton btnGuardarCamiseta;
    private javax.swing.JButton btnGuardarLeva;
    private javax.swing.JButton btnGuardarPantalonTela;
    private javax.swing.JButton btnIrPrincipal;
    private javax.swing.JComboBox<String> cmbCamisaCuadros;
    private javax.swing.JComboBox<String> cmbCamiseta;
    private javax.swing.JComboBox<String> cmbLeva;
    private javax.swing.JComboBox<String> cmbPantalonTela;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton rbtLCamisaCuadros;
    private javax.swing.JRadioButton rbtLCamiseta;
    private javax.swing.JRadioButton rbtLLeva;
    private javax.swing.JRadioButton rbtLPantalonTela;
    private javax.swing.JRadioButton rbtMCamisaCuadros;
    private javax.swing.JRadioButton rbtMCamiseta;
    private javax.swing.JRadioButton rbtMLeva;
    private javax.swing.JRadioButton rbtMPantalonTela;
    private javax.swing.JRadioButton rbtSCamisaCuadros;
    private javax.swing.JRadioButton rbtSCamiseta;
    private javax.swing.JRadioButton rbtSLeva;
    private javax.swing.JRadioButton rbtSPantalonTela;
    private javax.swing.JSpinner spnCamisaCuadros;
    private javax.swing.JSpinner spnCamiseta;
    private javax.swing.JSpinner spnLeva;
    private javax.swing.JSpinner spnPantalonTela;
    // End of variables declaration//GEN-END:variables
}
